# Generated by Django 5.2.11 on 2026-02-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='is_closed',
        ),
    ]
