# Generated by Django 5.2.11 on 2026-02-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_employeequerymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeequerymessage',
            name='sender_role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeequery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
