# Generated by Django 5.2.11 on 2026-02-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_employeequerymessage_sender_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeequery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('pending_admin', 'Pending Admin'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
